### PR TITLE
Update Architecture Diagram of XC3

### PR DESCRIPTION
**Pull request by muhdsaad**
Title: Update Architecture Diagram
        Link: #2

        [PS-1]
        - Added flow of lambda with SQS ans SES

### CODE REVIEW

**Review by yaseenzafar123 — APPROVED** [review]
LGTM

**Review by faheem-khau9 — APPROVED** [review]
LGTM

**Comment by SaadMohsinKhan-XCBG** [comment]
@muhdsaad Its the same as it was before. Whats the difference?

**Review by SaadMohsinKhan-XCBG — CHANGES_REQUESTED** [review]
@muhdsaad its the same as it was before

**Comment by muhdsaad** [comment]
> @muhdsaad Its the same as it was before. Whats the difference?

We added a bidirectional arrow from the lambda block to the "Schedule CW Event" icon to show that SQS and SES are used by the Monitoring & Alerting lambda.

**Comment by SaadMohsinKhan-XCBG** [comment]
@muhdsaad its pointing to the resource inventory, and not the monitoring and alerting lambda

**Comment by muhdsaad** [comment]
> @muhdsaad its pointing to the resource inventory, and not the monitoring and alerting lambda

@SaadMohsinKhan-XCBG I have updated the diagram accordingly here [910b875](https://github.com/XgridInc/xc3/pull/6/commits/910b875bc5c5876e10d4c65265c3558ef4d0d130)

**Review by SaadMohsinKhan-XCBG — APPROVED** [review]
@muhdsaad LGTM

**Pull request merged**
